src/com/eryansky/modules/sys/entity/User.java
/**
 *  Copyright (c) 2012-2014 http://www.eryansky.com
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 */
package com.eryansky.modules.sys.entity;

import com.eryansky.common.orm.PropertyType;
import com.eryansky.common.orm.annotation.Delete;
import com.eryansky.common.orm.entity.BaseEntity;
import com.eryansky.common.utils.ConvertUtils;
import com.eryansky.common.utils.collections.Collections3;
import com.eryansky.core.security.SecurityConstants;
import com.eryansky.modules.sys._enum.SexType;
import com.eryansky.utils.CacheConstants;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.google.common.collect.Lists;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

/**
 * 用户管理User.
 * @author 尔演&Eryan eryanwcp@gmail.com
 * @date 2013-3-21 上午12:28:04 
 *
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "T_BASE_USER")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE,region = CacheConstants.HIBERNATE_CACHE_BASE)
//jackson标记不生成json对象的属性 
@JsonIgnoreProperties (value = { "hibernateLazyInitializer" , "handler","fieldHandler",
        "resources","roles","defaultOrgan","organs"})
//逻辑删除注解标记 propertyName:字段名 value:删除标记的值（使用默认值"1"） type:属性类型
@Delete(propertyName = "status",type = PropertyType.I)
public class User
        extends BaseEntity
        implements Serializable {
	
    /**
     * 登录用户
     */
    private String loginName;
    /**
     * 登录密码
     */
    private String password;
    /**
     * 用户姓名
     */
    private String name;
    /**
     * 性别 女(0) 男(1) 保密(2) 默认：保密
     */
    private Integer sex = SexType.secrecy.getValue();

    /**
     * 邮件 以 ","分割
     */
    private String email;
    /**
     * 住址
     */
    private String address;
    /**
     * 住宅电话 以 ","分割
     */
    private String tel;
    /**
     * 手机号 以 ","分割
     */
    private String mobilephone;
    /**
     * 有序的关联对象集合
     */
    private List<Role> roles = Lists.newArrayList();
    /**
     * 有序的关联Role对象id集合
     */
    private List<Long> roleIds = Lists.newArrayList();

    /**
     * 资源 有序的关联对象集合
     */
    private List<Resource> resources = Lists.newArrayList();
    /**
     * 资源 id集合  @Transient
     */
    private List<Long> resourceIds = Lists.newArrayList();

    /**
     * 默认组织机构
     */
    private Organ defaultOrgan;
    /**
     * 默认组织机构 @Transient
     */
    private Long defaultOrganId;

    /**
     * 组织机构
     */
    private List<Organ> organs = Lists.newArrayList();

    /**
     * 组织机构ID集合 @Transient
     */
    private List<Long> organIds  = Lists.newArrayList();

    /**
     * 组织机构名称  @Transient
     */
    private String organNames;

    public User() {

    }

    @Column(name = "LOGIN_NAME",length = 36, nullable = false,unique = true)
    public String getLoginName() {
        return loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    @Column(name = "NAME",length = 36)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // 多对多定义
    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY)
    // 中间表定义,表名采用默认命名规则
    @JoinTable(name = "T_BASE_USER_ROLE", joinColumns = { @JoinColumn(name = "USER_ID") }, inverseJoinColumns = { @JoinColumn(name = "ROLE_ID") })
    // Fecth策略定义
//   @Fetch(FetchMode.SUBSELECT)
    // 集合按id排序.
    @OrderBy("id")
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE, region = CacheConstants.HIBERNATE_CACHE_BASE)
    public List<Role> getRoles() {
        return roles;
    }

    public void setRoles(List<Role> roles) {
        this.roles = roles;
    }

    @Column(name = "PASSWORD",length = 64, nullable = false)
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    @Column(name = "SEX")
    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * 性别描述.
     */
    @Transient
    public String getSexDesc() {
    	SexType ss = SexType.getSexType(sex);
    	String str = "";
    	if(ss != null){
    		str = ss.getDescription();
    	}
        return str;
    }
    @Column(name = "EMAIL",length = 64)
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    @Column(name = "ADDRESS",length = 255)
    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }
    @Column(name = "TEL",length = 36)
    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }
    @Column(name = "MOBILEPHONE",length = 36)
    public String getMobilephone() {
        return mobilephone;
    }

    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone;
    }

    /**
     * 用户拥有的角色名称字符串, 多个角色名称用','分隔.
     * <br>如果是超级管理员 直接返回 "超级管理员" AppConstants.ROLE_SUPERADMIN
     */
    @Transient
    // 非持久化属性.
    public String getRoleNames() {
    	Long superId = 1L;
	    if(superId.equals(this.getId())){
	        return SecurityConstants.ROLE_SUPERADMIN;
	    }
        return ConvertUtils.convertElementPropertyToString(roles, "name",
                ", ");
    }

    @SuppressWarnings("unchecked")
    @Transient
    public List<Long> getRoleIds() {
        if (!Collections3.isEmpty(roles)) {
            roleIds = ConvertUtils.convertElementPropertyToList(roles, "id");
        }
        return roleIds;
    }

    public void setRoleIds(List<Long> roleIds) {
        this.roleIds = roleIds;
    }

    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY)
    @JoinTable(name = "T_BASE_USER_RESOURCE", joinColumns = {@JoinColumn(name = "USER_ID")},
            inverseJoinColumns = {@JoinColumn(name = "RESOURCE_ID")})
//    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE,region = CacheConstants.HIBERNATE_CACHE_BASE)
    public List<Resource> getResources() {
        return resources;
    }

    public void setResources(List<Resource> resources) {
        this.resources = resources;
    }

    @Transient
    public List<Long> getResourceIds() {
        if (!Collections3.isEmpty(resources)) {
            resourceIds = ConvertUtils.convertElementPropertyToList(resources, "id");
        }
        return resourceIds;
    }

    public void setResourceIds(List<Long> resourceIds) {
        this.resourceIds = resourceIds;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DEFAULT_ORGANID")
    public Organ getDefaultOrgan() {
        return defaultOrgan;
    }

    public void setDefaultOrgan(Organ defaultOrgan) {
        this.defaultOrgan = defaultOrgan;
    }

    @Transient
    public Long getDefaultOrganId() {
        if(defaultOrgan != null){
            defaultOrganId = defaultOrgan.getId();
        }
        return defaultOrganId;
    }

    public void setDefaultOrganId(Long defaultOrganId) {
        this.defaultOrganId = defaultOrganId;
    }

    @Transient
    public String getDefaultOrganName(){
        String doName = null;
        if(defaultOrgan != null){
            doName = defaultOrgan.getName();
        }
        return doName;
    }

    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY)
    @JoinTable(name = "T_BASE_USER_ORGAN", joinColumns = {@JoinColumn(name = "USER_ID")},
            inverseJoinColumns = {@JoinColumn(name = "ORGAN_ID")})
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE,region = CacheConstants.HIBERNATE_CACHE_BASE)
    public List<Organ> getOrgans() {
        return organs;
    }

    public void setOrgans(List<Organ> organs) {
        this.organs = organs;
    }


    @Transient
    public List<Long> getOrganIds() {
        if(!Collections3.isEmpty(organs)){
            organIds =  ConvertUtils.convertElementPropertyToList(organs, "id");
        }
        return organIds;
    }

    public void setOrganIds(List<Long> organIds) {
        this.organIds = organIds;
    }

    @Transient
    public String getOrganNames() {
        return ConvertUtils.convertElementPropertyToString(organs, "name", ", ");
    }


}

WebRoot/WEB-INF/views/layout/about.jsp
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>
<ul>
<li>推荐使用1024*768及以上分辨率<br><br></li>
<li>支持Chrome、Firefox、IE6.0及以上版本浏览器浏览系统<br><br></li>
<div align="center"><a target="_blank" href="http://www.eryansky.com">www.eryansky.com</a></div><br>
<div align="center">版权所有 &copy; 2013 <a href="mailto:eryanwcp@gmail.com">尔演&Eryan</a></div>
</ul> 

WebRoot/WEB-INF/views/layout/app.jsp
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" %>
<%@ include file="/common/taglibs.jsp"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>essh桌面版</title>
<%@ include file="/common/meta.jsp"%>
<link rel="stylesheet" type="text/css" href="${ctx}/static/js/jquery/easyui-${ev}/themes/windows/app.css" />
<script type="text/javascript" src="${ctx}/static/js/jquery/easyui-${ev}/jquery.app.js" charset="utf-8"></script>
    <script type="text/javascript" src="${ctx}/static/js/session-keep.js" charset="utf-8"></script>
<script type="text/javascript">
$(function(){
});
</script>
    <script type="text/javascript" src="${ctx}/static/js/jquery/easyui-${ev}/initApp.js" charset="utf-8"></script>
</head>
<body>
</body>
</html>

WebRoot/WEB-INF/views/layout/center.jsp
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>
<%@ include file="/common/taglibs.jsp"%>
<script type="text/javascript">
var layout_center_tabs;
var layout_center_tabsMenu;
$(function() {
	layout_center_tabs = $('#layout_center_tabs').tabs();
	layout_center_tabsMenu = $('#layout_center_tabsMenu').menu({
		onClick : function(item) {
			var curTabTitle = $(this).data('tabTitle');
			var type = $(item.target).attr('type');
			//刷新
			if (type === 'refresh') {
				refresh(layout_center_tabs.tabs('getTab',curTabTitle));
				return;
			}
			//关闭
			if (type === 'close') {
				cancel();
				return;
			}

			var allTabs = layout_center_tabs.tabs('tabs');
			var closeTabsTitle = [];

			$.each(allTabs, function() {
				var opt = $(this).panel('options');
				if (opt.closable && opt.title != curTabTitle && type === 'closeOther') {
					closeTabsTitle.push(opt.title);
				} else if (opt.closable && type === 'closeAll') {
					closeTabsTitle.push(opt.title);
				}
			});

			for ( var i = 0; i < closeTabsTitle.length; i++) {
				layout_center_tabs.tabs('close', closeTabsTitle[i]);
			}
		}
	});

	//活动中的tip消息
	var activeTip;
	layout_center_tabs.tabs({
		fit : true,
		border : false,
        tools:'#layout_center_tabs_full-tools',
//        tools:[{
//            text:'',
//            iconCls:'icon-reload',
//            handler:function(){refresh()}
//        },{
//            text:'',
//            iconCls:'icon-cancel',
//            handler:function(){cancel()}
//        }],
		onContextMenu : function(e, title,index) {
			e.preventDefault();
			layout_center_tabsMenu.menu('show', {
				left : e.pageX,
				top : e.pageY
			}).data('tabTitle', title);
		},
		onAdd:function(title,index){
			//tip标题提示
			var tab = $(this).tabs('getTab',index).panel('options').tab;
			tab.unbind('mouseenter').bind('mouseenter',function(e){  
				activeTip = $(this).tooltip({  
	                position: 'top',  
	                content: title 
	            }).tooltip('show',e); 
	        });
		},
		onBeforeClose:function(title,index){
			if(activeTip){
				activeTip.tooltip('destroy'); 
			}
		}
	});
	
	//首页tip标题提示
	var indexTitle = "首页";
	layout_center_tabs.tabs('getTab',indexTitle).panel('options').tab.unbind('mouseenter').bind('mouseenter',function(e){  
		$(this).tooltip({  
            position: 'top',  
            content: indexTitle 
        }).tooltip('show',e); 
    });
});
//刷新
function refresh(selectedTab){
	var tab;
	if(selectedTab){
		tab = selectedTab;
	}else{
		tab = layout_center_tabs.tabs('getSelected');
	}
    if(tab == undefined){//未添加任何tab
        return;
    }
	var href = tab.panel('options').href;
	if (href) {/*说明tab是以href方式引入的目标页面*/
		var index = layout_center_tabs.tabs('getTabIndex', tab);
		layout_center_tabs.tabs('getTab', index).panel('refresh');
	} else {/*说明tab是以content方式引入的目标页面*/
		var panel = tab.panel('panel');
		var iframe = panel.find('iframe');
		layout_center_tabs.tabs('updateIframeTab',{      
			which:tab.panel('options').title,
			iframe:{src:iframe[0].src}
		}); 
	}
}
//关闭
function cancel(){
	var index = layout_center_tabs.tabs('getTabIndex', layout_center_tabs.tabs('getSelected'));
	var tab = layout_center_tabs.tabs('getTab', index);
    if(tab == undefined){//未添加任何tab
        return;
    }
	if (tab.panel('options').closable) {
		layout_center_tabs.tabs('close', index);
	} else {
		eu.showAlertMsg('[' + tab.panel('options').title + ']不可以被关闭.', 'error');
	}
}
/**
 *  全屏切换
 * @param flag
 */
function screenToggle(flag){
    var tools ;
    $(".easyui-tooltip").tooltip("hide","click");//  点击图标 隐藏tooltip提示
    //选中的tab页 防止 全屏导致的自动选择第一个tab
    var selectedTab = layout_center_tabs.tabs("getSelected");
    var selectedTab_Title = undefined;
    if(selectedTab){
        selectedTab_Title = selectedTab.panel("options").title;
    }

    if(flag){  //全屏
        tools = "#layout_center_tabs_unfull-tools";
        parent.indexLayout.layout("fullCenter");

    }else{ //退出全屏
        tools = "#layout_center_tabs_full-tools";
        parent.indexLayout.layout("unFullCenter");
    }
    layout_center_tabs.tabs({tools:tools});
    if(selectedTab_Title){
        layout_center_tabs.tabs("select",selectedTab_Title);
    }
}
</script>
<div id="layout_center_tabs" style="overflow: hidden;">
	<div id="layout_center_tabs_index" title="首页" data-options="href:'${ctx}/fileRedirect?toPage=layout/portal.jsp',iconCls:'icon-application'"></div>
</div>
<div id="layout_center_tabsMenu" style="width: 120px;display:none;">
	<div type="refresh" data-options="iconCls:'icon-reload'">刷新</div>
	<div class="menu-sep"></div>
	<div type="close" data-options="iconCls:'icon-cancel'">关闭</div>
	<div type="closeOther">关闭其他</div>
	<div type="closeAll">关闭所有</div>
</div>
<%--全屏工具栏--%>
<div id="layout_center_tabs_full-tools" style="display: none">
    <a href="#" class="easyui-linkbutton easyui-tooltip" title="全屏" data-options="iconCls:'icon-full_screen',plain:true"
       onclick="javascript:screenToggle(true);"></a>
    <a href="#" class="easyui-linkbutton easyui-tooltip" title="刷新" data-options="iconCls:'icon-reload',plain:true"
       onclick="javascript:refresh();"></a>
    <a href="#" class="easyui-linkbutton easyui-tooltip" title="关闭" data-options="iconCls:'icon-cancel',plain:true"
       onclick="javascript:cancel();"></a>
</div>
<%--退出全屏工具栏--%>
<div id="layout_center_tabs_unfull-tools" style="display: none;">
    <a href="#" class="easyui-linkbutton easyui-tooltip" title="退出全屏" data-options="iconCls:'icon-exit_full_screen',plain:true"
       onclick="javascript:screenToggle(false);"></a>
    <a href="#" class="easyui-linkbutton easyui-tooltip" title="刷新" data-options="iconCls:'icon-reload',plain:true"
       onclick="javascript:refresh();"></a>
    <a href="#" class="easyui-linkbutton easyui-tooltip" title="关闭" data-options="iconCls:'icon-cancel',plain:true"
       onclick="javascript:cancel();"></a>
</div>

WebRoot/WEB-INF/views/layout/index.jsp
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" %>
<%@ include file="/common/taglibs.jsp"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>后台管理主界面</title>
<%@ include file="/common/meta.jsp"%>
<script type="text/javascript" src="${ctx}/static/js/session-keep.js" charset="utf-8"></script>
    <script type="text/javascript" charset="utf-8">
        var indexLayout;
        $(function(){
            indexLayout = $("#indexLayout").layout();
        });
    </script>
</head>
<body id="indexLayout" class="easyui-layout" style="height: 100%;width: 100%;overflow-y: hidden;">
	<noscript>
		<div style="position: absolute; z-index: 100000; height: 2046px; top: 0px; left: 0px; width: 100%; background: white; text-align: center;">
			<img src="${ctx}/static/img/noscript.gif" alt='请开启脚本支持!' />
		</div>
	</noscript>
	<%-- north顶部Logo区域 --%>
	<div data-options="region:'north',border:false,split:false,href:'${ctx}/fileRedirect?toPage=layout/north.jsp'"
		style="height: 72px;overflow: hidden;">
	</div>

	<%-- west菜单栏 --%>
	<div data-options="region:'west',title:'导航菜单',split:false,href:'${ctx}/fileRedirect?toPage=layout/west.jsp'"
		style="width: 160px;overflow: hidden;">
	</div>

	<%-- center主面板 --%>
	<div data-options="region:'center',split:false,href:'${ctx}/fileRedirect?toPage=layout/center.jsp'" style="overflow: hidden;">
	</div>
	
	<%-- south底部 --%>
	<div data-options="region:'south',border:false,split:false,href:'${ctx}/fileRedirect?toPage=layout/south.jsp'"
		style="height: 20px;overflow: hidden;">
	</div>
</body>
</html>

WebRoot/WEB-INF/views/layout/north-password.jsp
<%@ page language="java" pageEncoding="UTF-8"
	contentType="text/html; charset=UTF-8"%>
<%@ include file="/common/taglibs.jsp"%>
<div>
	<form id="login_password_form" method="post" novalidate>
		<input type="hidden" id="login_password_form_id" name="id" value="${sessionInfo.userId}"></input>
		<div>
			<label>原始密码:</label> <input type="password" id="password"
				name="password" class="easyui-validatebox" required="true"
				missingMessage="请输入原始密码." validType="safepass"/>
		</div>
		<div>
			<label>新密码:</label> <input type="password" id="newPassword"
				name="newPassword" class="easyui-validatebox" required="true"
				missingMessage="请输入新密码." validType="safepass" />
		</div>
		<div>
			<label>确认新密码:</label> <input type="password" name="newPassword2"
				id="newPassword2" required="true" class="easyui-validatebox"
				missingMessage="请再次输入确认新密码." validType="equalTo['#newPassword']"
				invalidMessage="两次输入密码 不一致." />
		</div>
	</form>
</div>

WebRoot/WEB-INF/views/layout/north.jsp
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>
<%@ include file="/common/taglibs.jsp"%>
<script type="text/javascript">
var login_about_dialog;
var login_password_dialog;
var login_password_form;
function showAbout(){
    //弹出对话窗口
	login_about_dialog = $('<div/>').dialog({
		title:'关于我们',
		width : 420,
		height : 220,
		modal : true,
		href : '${ctx}/fileRedirect?toPage=layout/about.jsp',
		buttons : [{
			text : '关闭',
			iconCls : 'icon-cancel',
			handler : function() {
				login_about_dialog.dialog('destroy');
			}
		}],
		onClose : function() {
			$(this).dialog('destroy');
		}
	}).dialog('open');
  	$(".panel-title").css('text-align', 'center');
}
  
 function initLoginPasswordForm(){
   login_password_form = $('#login_password_form').form({
		url: '${ctx}/sys/user!updateUserPassword',
		onSubmit: function(param){  
	        param.upateOperate = '1';  
	        return $(this).form('validate');
	    }, 
		success: function(data){
			var json = eval('('+ data+')');  
			if (json.code == 1){
				login_about_dialog.dialog('close');	
				eu.showMsg(json.msg);//操作结果提示
			} else if(json.code == 2){
				$.messager.alert('提示信息！', json.msg, 'warning',function(){
					var userId = $('#login_password_form_id').val();
					$(this).form('clear');
					$('#login_password_form_id').val(userId);
					if(json.obj){
						$('#login_password_form input[name="'+json.obj+'"]').focus();
					}
				});
			}else {
				eu.showAlertMsg(json.msg,'error');
			}
		}
	});
}
  
   function editLoginUserPassword(){
    //弹出对话窗口
	login_about_dialog = $('<div/>').dialog({
		title:'修改用户密码',
		width : 460,
		height : 240,
		modal : true,
		href : '${ctx}/fileRedirect?toPage=layout/north-password.jsp',
		buttons : [{
			text : '保存',
			iconCls : 'icon-save',
			handler : function() {
				login_password_form.submit();;
			}
		},{
			text : '关闭',
			iconCls : 'icon-cancel',
			handler : function() {
				login_about_dialog.dialog('destroy');
			}
		}],
		onClose : function() {
			$(this).dialog('destroy');
		},
		onLoad:function(){
			initLoginPasswordForm();
		}
	}).dialog('open');
   }
//注销
function logout() {
	$.messager.confirm('确认提示！', '您确定要退出系统吗？', function(r) {
		if (r) {
			window.location.href = "${ctx}/login/logout";
		}
	});
}
    //切换到桌面版
    function toApp(){
        var themeType_index = "app";
        $.cookie('themeType', themeType_index, {
            expires : 7
        });
        window.location.href = '${ctx}/login/index?theme='+themeType_index;
    }
</script>
<div style="background-image: url(${ctx}/static/img/top_bg.png); background-repeat: repeat-x;">
    <div style="float: left;">
	    <img alt="essh" title="永远的小女儿" class="easyui-tooltip" data-options="position:'right'" src="${ctx}/static/img/essh_logo.png">
	</div>
	<div style="float: right; position: absolute; bottom: 20px; right: 10px">
	    <div style="text-align: right;">您好,<span style="color: red;">${sessionInfo.loginName}</span>[${sessionInfo.roleNames}] 欢迎您！</div>
		<a href="javascript:void(0);" class="easyui-menubutton" menu="#layout_north_pfMenu" iconCls="icon-user_red">更换皮肤</a>
		<div id="layout_north_pfMenu" style="width: 120px; display: none;">
			<div onclick="eu.changeTheme('bootstrap');">bootstrap</div>
			<div onclick="eu.changeTheme('default');">蓝色</div>
			<div onclick="eu.changeTheme('gray');">灰色</div>
			<div onclick="eu.changeTheme('black');">黑色</div>
			<div onclick="eu.changeTheme('metro');">metro</div>
		</div>
	
	    <a href="javascript:void(0);" class="easyui-menubutton" menu="#layout_north_kzmbMenu" iconCls="icon-help">控制面板</a>
		<div id="layout_north_kzmbMenu" style="width: 100px; display: none;">
			<div onclick="editLoginUserPassword();" iconCls="icon-edit">修改密码</div>
			<div class="menu-sep"></div>
            <div onclick="toApp();">切换到桌面版</div>
            <div class="menu-sep"></div>
			<div onclick="" data-options="iconCls:'icon-help'">帮助</div>
			<div onclick="showAbout();">关于</div>
		</div>
		
		<a href="javascript:void(0);" class="easyui-menubutton" menu="#layout_north_logoutMenu" iconCls="icon-back">安全退出</a>
		<div id="layout_north_logoutMenu" style="width: 100px; display: none;">
			<div onclick="logout();"  data-options="iconCls:'icon-lock'">注销</div>
		</div>
	</div>
</div>

WebRoot/WEB-INF/views/layout/portal-about.jsp
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>
<%@ include file="/common/taglibs.jsp"%>
<ul>
<li>essh是一个EasyUI整站示例系统.<br><br></li>
<li>前台由EasyUI1.3.6编写，后台是Java编写，应用框架struts2+spring3+hibernate+ehcache.<br><br></li>
<li>要求:JDk6 源码包中已提供MySQL5.1 Oracle10G的脚本.<br><br></li>
<div align="center">版权所有 &copy; 2014 <a href="mailto:eryanwcp@gmail.com">尔演&Eryan</a></div>
</ul> 

WebRoot/WEB-INF/views/layout/south.jsp
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>
<div align="center" style="height:20px;background: #f2f2f2;">
	版权所有 &copy; 2014 <a href="mailto:eryanwcp@gmail.com">尔演&Eryan</a>
</div>